apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: spring-github-nexus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: nexus-docker-nexus.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap/raisa-tes:c944e77fa04a57d7e54c6fd682ac74cf5e2c3878@sha256:61d813870280e2fdd6da44fdddf50ef46352e49fd4c57ce891d67c4ffca03356
          name: container-image
