apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: spring-github-nexus
  janus-idp.io/tekton: spring-github-nexus
  backstage.io/kubernetes-id: spring-github-nexus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: spring-github-nexus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
