apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: spring-github-nexus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-github-nexus 
  name: spring-github-nexus
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: spring-github-nexus 
